services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Andchir\TwigVisualBundle\:
        resource: '../../*'
        exclude: '{DependencyInjection,Form,Document,Resources}'

    Andchir\TwigVisualBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    twig-visual:
        class: Andchir\TwigVisualBundle\Service\TwigVisualService
        arguments: ['@service_container']
        tags: ['controller.service_arguments']
        public: true
