services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Andchir\TwigVisualBundle\:
        resource: '../../*'
        exclude: '{DependencyInjection,Form,Document,Resources,Tests}'

    Andchir\TwigVisualBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    twigvisual:
        class: Andchir\TwigVisualBundle\Service\TwigVisualService
        public: true
        arguments: ['@parameter_bag', '@twig', '@translator', '@kernel']
        
